TebLocalPlannerROS:

 odom_topic: odom
 map_frame: /map

 # Trajectory
 teb_autosize: True
 dt_ref: 0.5
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: False
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 5.0
 feasibility_check_no_poses: 5
 publish_feedback: False # (bool, default: false) #Publish planner feedback containing the full trajectory and a list of active obstacles (should be enabled only for evaluation or debugging). See list of publishers above. New in version 0.2.2
 shrink_horizon_backup: false # (bool, default: true) #Allows the planner to shrink the horizon temporary (50%) in case of automatically detected issues. New in version 0.2.3

 # Robot
 max_vel_x: 0.3
 max_vel_x_backwards: 0.15
 max_vel_y: 0.1
 max_vel_theta: 0.1
 acc_lim_x: 2.5
 acc_lim_y: 0.5
 acc_lim_theta: 0.5
 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "line"
   # radius: 0.72
   # front_offset: 1.15 # for type "two_circles"
   # front_radius: 0.5 # for type "two_circles"
   # rear_offset: 0.0 # for type "two_circles"
   # rear_radius: 0.72 # for type "two_circles"
   line_start: [-0.45, 0.0] # for type "line"
   line_end: [1.375, 0.0] # for type "line"
   # vertices: [[0.4,0.0],[0.35,0.35],[-0.2,0.4],[-0.45,0.0],[-0.2,-0.4],[0.35,-0.35]] # COB only
   # vertices: [[1.375,0.225], [0.4,0.225], [0.35,0.35],[-0.2,0.4],[-0.45,0.0],[-0.2,-0.4],[0.35,-0.35], [0.4,-0.225], [1.375,-0.225]] # COB + cart

 # GoalTolerance
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False

 # Obstacles
 min_obstacle_dist: 0.55 # This value must also include our robot radius, since footprint_model is set to "point".
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 0.6
 obstacle_poses_affected: 10
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
 no_inner_iterations: 3
 no_outer_iterations: 3
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.05
 weight_max_vel_x: 1
 weight_max_vel_y: 1
 weight_max_vel_theta: 1
 weight_acc_lim_x: 0
 weight_acc_lim_theta: 0
 weight_kinematics_nh: 1000  #1000
 weight_kinematics_forward_drive: 0.001  #0.001
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_shorted_path: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 selection_alternative_time_cost: False # not in use yet

 # Homotopy Class Planner
 enable_homotopy_class_planning: false
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 2
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
