joint_names: [gripper_right_finger_1_joint, gripper_right_finger_2_joint]
action_name: /gripper_right/joint_trajectory_controller/follow_joint_trajectory
service_ns: /gripper_right/driver
default_acc: 0.3

# single positions
fully_open: [[0.85, 0.0]]
